<head>
</head>
<body>
<center>
    
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    <p class="text-right"> <a class="btn btn-primary" href="<?php echo $this->url(array("module"=>"admin","controller"=>"slider","action"=>"new"),null,true)?>">Cadastrar Imagem</a></p>
    <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
   <tr>
        <th><center>Nome</center></th>
        <th><center>Descrição</center></th>        
        <th><center>Imagem</center></th>
        <th><center>Açoes</center></th>
   </tr>
   <?php foreach($this->paginator AS $key => $slider):?>
   <tr>
      <td><center><?php echo $slider['nome']?></center></td>
        <td><center><?php  echo $slider['descricao']?></center></td>        
    <td><center><img src="../images/<?php echo urldecode($slider['nome'])?>" alt="<?php echo $slider['descricao']?>" width="60%" height="60%"></center></td>
      <td><center>
         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"slider","action"=>"edit","id"=>"{$slider['idImagens']}"),null,true)?>" title="Editar Cadastro"><i class='icon-pencil'></i></a> 
         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"slider","action"=>"delete","id"=>"{$slider['idImagens']}"),null,true)?> " title="Deletar Cadastro" onclick='if (confirm("Deseja remover o cadastro?")) { document.form.submit(); } return false;'><i class='icon-remove'></i></a> 
         </center>
      </td>
   </tr>
   <?php endforeach;?>
</table>
    
</center>
</body>