<style>
    header{
        background-image:url('/images/fundo_topo.png');
/*        -khtml-opacity:.50; 
        -moz-opacity:.50; 
        -ms-filter:"alpha(opacity=50)";
         filter:alpha(opacity=50);
         filter: progid:DXImageTransform.Microsoft.Alpha(opacity=0.5);
         opacity:.50; */
    }
</style>
<header> 
    <div class="container_12">
        <div class="grid_12"> 
         <h1> <img src="/images/LogoLuh.png" width="100px"> <a href="index.html"><img src="/images/luh.png" alt="Luana Galian Nutricionista"></a> </h1>
         <div class="menu_block">
                <nav  class="" >
                 <ul class="sf-menu">
                    <li class="current"><a href="<?php echo $this->url(array("controller"=>"index","action"=>"index"),null,true)?>">Home</a></li>
                    <li><a href="<?php echo $this->url(array("controller"=>"blog","action"=>"index"),null,true)?>">Blog</a></li>
                    <li><a href="<?php echo $this->url(array("controller"=>"receitas","action"=>"index"),null,true)?>">Receitas</a></li>
                    <li><a href="<?php echo $this->url(array("controller"=>"contato","action"=>"index"),null,true)?>">Contato</a></li>
                  </ul>
                </nav>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
        </div>
    </div>
</header>
