<header> 
    <div class="container_12">
        <div class="grid_12"> 
         <h1><a href="index.html"><img src="images/luh.png" alt="Luana Galian Nutricionista"></a> </h1>
         <div class="menu_block">
                <nav  class="" >
                 <ul class="sf-menu">
                    <li class="current"><a href="<?php echo $this->url(array("controller"=>"index","action"=>"index"),null,true)?>">Home</a></li>
                    <li><a href="<?php echo $this->url(array("controller"=>"blog","action"=>"index"),null,true)?>">Blog</a></li>
                    <li><a href="<?php echo $this->url(array("controller"=>"receitas","action"=>"index"),null,true)?>">Receitas</a></li>
                    <li><a href="<?php echo $this->url(array("controller"=>"contato","action"=>"index"),null,true)?>">Contato</a></li>
                  </ul>
                </nav>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
        </div>
    </div>
</header>