
    <div class="grid_8 prefix_2">
      <div id="mi-slider" class="mi-slider">
          <ul>
            <li class=""><a href="#"><img src="/images/fruit1.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/fruit2.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/fruit3.jpg" alt=""></a></li>
          </ul>
          <ul>
            <li class=""><a href="#"><img src="/images/veg1.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/veg2.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/veg3.jpg" alt=""></a></li>
          </ul>
          <ul>
            <li class=""><a href="#"><img src="/images/meat1.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/meat2.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/meat3.jpg" alt=""></a></li>
          </ul>
          <ul>
            <li class=""><a href="#"><img src="/images/dier1.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/dier2.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/dier3.jpg" alt=""></a></li>
          </ul>
        
          <nav>
            <a href="#">fruits</a>
            <a href="#">vegetables</a>
            <a href="#">meat</a>
            <a href="#">dairy</a>
          </nav>
        </div>
    </div>
    <div class="clear"></div>
    <div class="grid_8">
      <h3>Seja bem vindo</h3>
      <img src="images/page1_img1.jpg" alt="" class="img_inner fleft">
      <div class="extra_wrapper">
        <p><a href="http://www.templatemonster.com/category/agriculture-website-templates/" rel="nofollow">Find more themes of this kind at the category of premium Agriculture Website Templates.</a></p>
      </div>
      <div class="clear"></div>
      Aliquam nibh ante, egestas id dictum a, commodo luctus libero. Praesent faucibus malesuada faucibus. Donecyl laoreet metus id laoreet malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetu orci sed nulla facilisis consequat. Curabitur vel lorem sit amet nulla ullamcorper fermentum. 
      <div class="grid_4 alpha">
        <div class="banner maxheight">
          <h3><a href="#">100% Eco &amp; <br> Organic</a></h3>
        </div>
        <h3>Our Mission</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis erat mattis neque facilisis, sit amet ultriciesyt erat rutrum. Cras facilisis, nulla vel viverra auctor, leo ame magna sodales felis, quis malesuada.</p>
        <ul class="list">
          <li><a href="#">Duis massa elit, auctor non pellentesque vel.</a></li>
          <li><a href="#">Nullam eget dignissim nisi, aliquam feugiat nibh. </a></li>
          <li><a href="#">Ut nisi nibh, sagittis ut semper elementum.</a></li>
          <li><a href="#">Pellentesque a odiohasellus vitae libero vel.</a></li>
          <li><a href="#">Justo pretium dignissimteger semper in estgue.</a></li>
          <li><a href="#"> In laoreet lacus eros, vel pulvinar urna ultut.</a></li>
        </ul>
      </div>
      <div class="grid_4 omega">
        <div class="banner b1 maxheight">
          <h3><a href="#">Control of <br> the Quality </a></h3>
        </div>
        <h3>What We Offer</h3>
        <p>Retrolom ipsum dolor sit met, consectetur ipiscing elit. In mollis erat mattis neque facilisis, sit amet ultriciesert erat rutrum. Bras facilisis, nulla vel viverra aucto ame magna sodales felis, quis  nibh odio. </p>
        <ul class="list">
          <li><a href="#">Setrolis assa elit, auctor non  reto lo. </a></li>
          <li><a href="#">Master lam eget dignissim nliam feugiat nibherty. </a></li>
          <li><a href="#">Do nisi nibh  ut semper ntumertolillente derto.</a></li>
          <li><a href="#">Sertloque a odiohasellus vitae libero velertlo fer.</a></li>
          <li><a href="#">Monrilo sto pretium dignissimerwtoli moloer. </a></li>
          <li><a href="#">Ontnteger semper in estgue destro.</a></li>
        </ul>
      </div>
      <div class="clear"></div>
    </div>
    <div class="grid_3 prefix_1">
      <!-- Elastislide Carousel -->
     
          <ul id="carousel" class="elastislide-list">
            <li><a href="#"><img src="/images/page1_img2.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/page1_img3.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/page1_img4.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/page1_img2.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/page1_img3.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/page1_img4.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/page1_img2.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/page1_img3.jpg" alt=""></a></li>
            <li><a href="#"><img src="/images/page1_img4.jpg" alt=""></a></li>
          </ul>
          <!-- End Elastislide Carousel -->
           <div class="car_div">
            <div class="title">Depoimentos de pacientes</div>
          <ul id="carousel1" class="">
            <li>“Lorem ipsum dolor sit amet, tetur adipiscing elit. In ollis erat matti neque facilisis, sit amet .”</li>
            <li>"Retrolom ipsum dolor sit met, consectetur ipiscing elit. In mollis erat mattis neque."</li>
            <li>"Aliquam nibh ante, egestas id dictum a, commodo luctus libero. Praesent faucibus."</li>
        </ul>
        <a href="#" class="prev1"></a><a href="#" class="next1"></a>
        </div>
    </div>