<head>
</head>
<body>
<center>
    
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    <p class="text-right"> <a class="btn btn-primary" href="<?php echo $this->url(array("module"=>"admin","controller"=>"sponsor","action"=>"new"),null,true)?>">Cadastrar Patrocinador</a></p>
    <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
   <tr>
        <th><center>Nome</center></th>
        <th><center>Descrição</center></th>        
        <th><center>Logo</center></th>
        <th><center>Status</center></th>
        <th><center>Data de Inclusao</center></th>
        <th><center>Alterado por</center></th>
        <th><center>Data de Alteraçao</center></th>
        <th><center>Açoes</center></th>
   </tr>
   <?php foreach($this->paginator AS $key => $sponsor):?>
   <tr>
      <td><center><?php echo $sponsor['Patrocinador']?></center></td>
        <td><center><?php  echo $sponsor['descricao']?></center></td>        
    <td><center><img src="../images/<?php echo urldecode($sponsor['nome'])?>" alt="<?php echo $sponsor['descricao']?>" width="60%" height="60%"></center></td>
        <td><center>Status</center></td>
        <td><center><?php echo$sponsor['dtInclusao']?></center></td>
        <td><center><?php  echo $sponsor['usrAlterou']?></center></td>
        <td><center><?php echo$sponsor['dtAlteracao']?></center></td>
      <td><center>
         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"sponsor","action"=>"show","id"=>"{$sponsor['idPatrocinador']}"),null,true)?>" title="Visualizar Cadastro"><i class='icon-eye-open'> </i></a>
         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"sponsor","action"=>"edit","id"=>"{$sponsor['idPatrocinador']}"),null,true)?>" title="Editar Cadastro"><i class='icon-pencil'></i></a> 
         </center>
      </td>
   </tr>
   <?php endforeach;?>
</table>
    
</center>
</body>