<div class="grid_12">
      <h3>Our BLog</h3>      </div>
      <div class="grid_7">
        <div class="blog">
          <img src="images/page3_img1.jpg" alt="" class="img_inner fleft">
          <div class="extra_wrapper">
            <h4><a href="#">Vivamus at magna non nunc </a></h4>
            <time datetime="2013-01-01">October 13, 2013</time>Lorem ipsum dolor sit aconsectetur adipiscing elit. In mollis erat mat. neque facilisis, sit amet ultricies erat rutrum. Cras facilisis, nulla vel viverra auctor, leo ame magna sodales felis, quis malesuada nibh odio ut velit. Proin pharetra luctus dia a scelerisque eros. 
            <br>
            <a href="#" class="link1">Learn More</a>
          </div>
        </div>
        <div class="blog">
          <img src="images/page3_img2.jpg" alt="" class="img_inner fleft">
          <div class="extra_wrapper">
            <h4><a href="#">Quisque viverra nulla nun</a></h4>
            <time datetime="2013-01-01">October 13, 2013</time>Cobeem ipsum dolor sit aconsectetur adipiscing elit. In mollis erat mat. neque facilisis, sit amet ultricies erat rutrum. Cras facilisis, nulla vel viverra auctor, leo ame magna sodales felis, quis malesuada nibh odio ut velit. Proin pharetra luctus dia.
            <br>
            <a href="#" class="link1">Learn More</a>
          </div>
        </div>
        <div class="blog">
          <img src="images/page3_img3.jpg" alt="" class="img_inner fleft">
          <div class="extra_wrapper">
            <h4><a href="#">Integer convallis orci vel </a></h4>
            <time datetime="2013-01-01">October 13, 2013</time>Lorem ipsum dolor sit aconsectetur adipiscing elit. In mollis erat mat. neque facilisis, sit amet ultricies erat rutrum. Cras facilisis, nulla vel viverra auctor, leo ame magna sodales felis, quis malesuada nibh odio ut velit. Proin pharetra luctus dia a scelerisque eros. 
            <br>
            <a href="#" class="link1">Learn More</a>
          </div>
        </div>
        <div class="blog">
          <img src="images/page3_img4.jpg" alt="" class="img_inner fleft">
          <div class="extra_wrapper">
            <h4><a href="#">Amus at magna non nuno </a></h4>
            <time datetime="2013-01-01">October 13, 2013</time>Hew ipsum dolor sit aconsectetur adipiscing elit. In mollis erat mat. neque facilisis, sit amet ultricies erat rutrum. Cras facilisis, nulla vel viverra auctor, leo ame magna sodales felis, quis malesuada nibh odio ut velit. Proin pharetra luctus dia a scelerisqu.
            <br>
            <a href="#" class="link1">Learn More</a>
          </div>
        </div>

    </div>
    <div class="grid_4 prefix_1">
      <h4>Categories</h4>
      <ul class="list">
        <li><a href="#">Duis massa elit, auctor non pellentesque vel.</a></li>
        <li><a href="#">Nullam eget dignissim nisi, aliquam feugiat nibh. </a></li>
        <li><a href="#">Ut nisi nibh, sagittis ut semper elementum.</a></li>
        <li><a href="#">Pellentesque a odiohasellus vitae libero vel.</a></li>
        <li><a href="#">Justo pretium dignissieger semper in estgue.</a></li>
        <li><a href="#"> In laoreet lacus eros, vel pulvinar urna ultut.</a></li>
      </ul>
      <h4 class="head1">Recent Posts</h4>
      <div class="post">
        <div class="l_blox">
          <img src="images/page3_img5.jpg" alt="">
          <time datetime="2013-01-01">2013-07-04</time>
        </div>
        <div class="extra_wrapper"><a href="#">Cras facilisis, nulla vel viverra auctor, leo ame magna dales felis, quis malesuada nibher odio ut velit. Proin pharetra li luctus dia a scelerisque mi
convallis accumsan. </a></div>
      </div>
      <div class="post">
        <div class="l_blox">
          <img src="images/page3_img6.jpg" alt="">
          <time datetime="2013-01-01">2013-08-07</time>
        </div>
        <div class="extra_wrapper"><a href="#">Joas facilisis, nulla vel viverra auctor, leo ame magna dales felis, quis malesuada nibher odio ut velit. Proin pharetra li luctus dia a scelerisque mi
convallis accumer. </a></div>
      </div>
      <h4 class="head1">Recent Comments</h4>
      <div class="comm">
        <div class="user">
          <img src="images/page3_img7.jpg" alt="" class="img_inner fleft">
          <div class="extra_wrapper">
            <p><a href="#">Admin</a></p>
            <time datetime="2013-01-01">September 14, 2013</time>
          </div>
        </div>
        Maecenas vehicula egestas venenatis.  Fertolo milotti.
Duis massa elit, auctor non pellentesque vel.
      </div>
      <div class="comm">
        <div class="user">
          <img src="images/page3_img7.jpg" alt="" class="img_inner fleft">
          <div class="extra_wrapper">
            <p><a href="#">Admin</a></p>
            <time datetime="2013-01-01">September 14, 2013</time>
          </div>
        </div>
        Neraecenas vehicula egestas venenatis. Fertolo milottiis massa elit, auctor non pellentesq.
      </div>
    </div>
  </div>
</div>
<!--==============================footer=================================-->
<div class="bottom_block">
    <div class="container_12">
      <div class="grid_10 prefix_1">
        <div class="column"><a href="#">Nossa Equipe</a></div>
        <div class="column"><a href="#">FAQs</a></div>
        <div class="column"><a href="#">Contato</a></div>
        <div class="clear"></div>
          <div class="socials">
            <a href="#"><i class=" icon-facebook"></i></a>
            <a href="#"><i  class="icon-twitter"></i></a>
            <a href="#"><i class=" icon-google-plus "></i></a>
            <a href="#"><i class=" icon-pinterest"></i></a>
          </div>
        
      </div>