<head>
</head>
<body>
<center>
    
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
   <tr>
        <th><center>Diretório</center></th>
        <th><center>Nome do Arquivo</center></th>
        <th><center>Logo</center></th>        
        <th><center>Data de Alteraçao</center></th>
        <th><center>Açoes</center></th>
   </tr>
   <?php foreach($this->paginator AS $key => $logo):?>
   <tr>
        <td><center><?php echo $logo['diretorio']?></center></td>
        <td><center><?php  echo $logo['nome']?></center></td>        
        <td style="background-color: <?php echo $logo['corFundo']?>"><center><img src=".<?php echo $logo['diretorio']?><?php echo urldecode($logo['nome'])?>" alt="<?php echo $logo['nome']?>" width="60%" height="60%"></center></td>
        <td><center><?php echo $logo['dtAlteracao']?></center></td>
      <td><center>
         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"logo","action"=>"edit"),null,true)?>" title="Editar Cadastro"><i class='icon-pencil'></i></a> 
         </center>
      </td>
   </tr>
   <?php endforeach;?>
</table>
    
</center>
</body>