<?php
$dbGrupo = new Admin_Model_DbTable_Grupo();
?>
<head>
</head>
<body>
<center>
    
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    <p class="text-right"> <a class="btn btn-primary" href="<?php echo $this->url(array("module"=>"admin","controller"=>"users","action"=>"new"),null,true)?>">Cadastrar Usuario</a></p>
    <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
   <tr>
        <th><center>Nome</center></th>        
        <th><center>login</center></th>        
        <th><center>Data de Inclusao</center></th>
        <th><center>Alterado por</center></th>
        <th><center>Data de Alteraçao</center></th>
        <th><center>Grupo</center></th>
        <th><center>Açoes</center></th>
   </tr>
   <?php foreach($this->paginator AS $key => $user):?>
   <tr>
        <td><center><?php  echo $user['nome']?></center></td>        
        <td><center><?php  echo $user['login']?></center></td>
        <td><center><?php echo$user['dtInclusao']?></center></td>
        <td><center>Alterado por</center></td>
        <td><center><?php echo$user['dtAlteracao']?></center></td>
    <td><center><?php $grupo = $dbGrupo->getListaGrupo( $user['grupo'] );
                echo $grupo[0]['value']; ?>
    </center></td>
      <td><center>
         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"users","action"=>"show","id"=>"{$user['idUsuario']}"),null,true)?>" title="Visualizar Cadastro"><i class='icon-eye-open'> </i></a>
         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"users","action"=>"edit","id"=>"{$user['idUsuario']}"),null,true)?>" title="Editar Cadastro"><i class='icon-pencil'></i></a> 
         </center>
      </td>
   </tr>
   <?php endforeach;?>
</table>
    
</center>
</body>